### PR TITLE
Feature/OIDC

### PR DESCRIPTION
**Pull request by sughics**
OIDC integrarion, openapi specs

### CODE REVIEW

**Comment by sughics** [comment]
API specs for APi Gateway have been set up here https://github.com/AtlasOfLivingAustralia/aws-apig-cognito/blob/test/collectory/app_setup/apis/app-rest.yaml.  Optional API paths have been set to be proxied where applicable (see specieslist and bie-index api gateways specs for similar examples in the linked repo)

**Comment by sughics** [comment]
When attempting to replicate issue #151 , I noticed that the user info extraction and its usage to determine the users role and admin status is not working as expected after the OIDC upgrade. I've made change the related methods in and usages in CollectoryAuthService and CollectoryTagLib to resolve this issue as well as issue #151 and tested to make sure that the content is accessible/inassibe based on the user's logged in stauts and roles. 
Could you please review these changes @adam-collins  ?

**Comment by vjrj** [comment]
Any possibility to make this compatible with pre-OIDC auth systems? We are trying to migrate from `ala-collectory` to `collectory` since months ago but we couldn't because of the different issues still present in `collectory` (several with PR pending to review/merge).

**Comment by sughics** [comment]
@vjrj  are you referring to #151 specifically? I can take a look at the current non-oidc version and see if I can find a fix.  
Also, if you need the PRs reviewed please let me know/assign to me. Thanks

**Comment by vjrj** [comment]
Yes, I was thinking in #151. I'll assign you some of the PRs (please feel free to reassign them). Thanks indeed.

**Comment by sughics** [comment]
> Yes, I was thinking in #151. I'll assign you some of the PRs (please feel free to reassign them). Thanks indeed.

@vjrj , here's the non-oidc fix for issue #151 . PR #154 . Feel free to review and merge

**Comment by sughics** [comment]
There seems to be some custom apiKey authentication in a few places. I will need to update that before this PR can be merged. https://github.com/AtlasOfLivingAustralia/collectory/blob/9703b769e2e2291ba74bf7cfdf73fc9d069e74d4/grails-app/controllers/au/org/ala/collectory/DataController.groovy#L85

**Review by adam-collins — APPROVED** [review]
Looks ok to me

**Pull request merged**
